apiVersion: apps/v1
kind: Deployment
metadata:
  name: protection
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tasks: protection
  template:
    metadata:
      labels:
        tasks: protection
    spec:
      containers:
      - name: protection
        image: docker.io/library/prot-container:l1
---
apiVersion: v1
kind: Service
metadata:
  name: protection-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    tasks: protection
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30004
