apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: docker.io/library/tasks-container:l2

---
apiVersion: v1
kind: Service
metadata:
  name: tasks-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: tasks
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-grpc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: tasks
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30003

