apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tasks: zvm
  template:
    metadata:
      labels:
        tasks: zvm
    spec:
      containers:
      - name: tunnel
        image: docker.io/library/tunnel-container:l1
---
apiVersion: v1
kind: Service
metadata:
  name: tunnel-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    tasks: zvm
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
