// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"
)

type Querier interface {
	// -- name: GetRunningVPGs :many
	// SELECT * FROM vpg WHERE status = 1;
	AddVpg(ctx context.Context, arg AddVpgParams) (Vpg, error)
	GetNonReadyVPGs(ctx context.Context) ([]Vpg, error)
	UpdateStatus(ctx context.Context, arg UpdateStatusParams) error
}

var _ Querier = (*Queries)(nil)
